version: '3.1'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: verysecretpassword
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  bot:
    #image: docker.pkg.github.com/osoderholm/svenska-yle-bot/svenska-yle-bot:latest
    build:
      context: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bot
      DB_USER: bot
      DB_PASSWORD: verysecretpassword
      TG_API_TOKEN: "telegram:api-token"
      CHANNEL_SUBSCRIBERS: "@svenskayletest"
    restart: on-failure
