name: Docker registry

on: [push]
  #push:
  #  branch:
  #    - master
  #  tags:
  #    - 'v*'

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: ghcr.io

      - name: Build
        if: success()
        run: docker build -t ghcr.io/${{ github.repository }}/svenska-yle-bot:${IMAGE_TAG} -t ghcr.io/${{ github.repository }}/svenska-yle-bot:$(echo ${GITHUB_SHA} | cut -c1-8) .

      - name: Push to docker hub :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ghcr.io/${{ github.repository }}/svenska-yle-bot:${IMAGE_TAG}

      - name: Push to docker hub :hash
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ghcr.io/${{ github.repository }}/svenska-yle-bot:$(echo ${GITHUB_SHA} | cut -c1-8)
